### ISSUE TITLE
Some use of commons-io IOUtils.closeQuietly are not jdk6 compatible : java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by nickho** [wro4j/wro4j#1012]
Hello,
When deploying on Websphere 7 (base version jdk6 IBM) i have the following stack trace when wro try to load the fontawsome font files referenced from the css in a webjar (loaded with classpath locator).
```
[14/04/16 10:09:08:269 CEST] 00000024 webapp        E com.ibm.ws.webcontainer.webapp.WebApp logError SRVE0293E: [Erreur du servlet]-[null] : java.lang.IncompatibleClassChangeError
	at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
	at ro.isdc.wro.model.resource.locator.wildcard.JarWildcardStreamLocator.locateStreamFromJar(JarWildcardStreamLocator.java:167)
	at ro.isdc.wro.model.resource.locator.wildcard.JarWildcardStreamLocator.locateStream(JarWildcardStreamLocator.java:62)
	at ro.isdc.wro.model.resource.locator.ClasspathUriLocator.locateWildcardStream(ClasspathUriLocator.java:131)
	at ro.isdc.wro.model.resource.locator.ClasspathUriLocator.locateWildcardStream(ClasspathUriLocator.java:121)
	at ro.isdc.wro.model.resource.locator.ClasspathUriLocator.locate(ClasspathUriLocator.java:85)
	at ro.isdc.wro.model.resource.locator.factory.InjectableUriLocatorFactoryDecorator.locate(InjectableUriLocatorFactoryDecorator.java:37)
	at ro.isdc.wro.http.handler.ResourceProxyRequestHandler.serveProxyResourceUri(ResourceProxyRequestHandler.java:90)
	at ro.isdc.wro.http.handler.ResourceProxyRequestHandler.handle(ResourceProxyRequestHandler.java:70)
	at ro.isdc.wro.http.handler.LazyRequestHandlerDecorator.handle(LazyRequestHandlerDecorator.java:51)
	at ro.isdc.wro.http.WroFilter.handledWithRequestHandler(WroFilter.java:318)
	at ro.isdc.wro.http.WroFilter.doFilter(WroFilter.java:294)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:188)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:116)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain._doFilter(WebAppFilterChain.java:77)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:908)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:997)
	at com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor.invokeFilters(DefaultExtensionProcessor.java:1062)
	at com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor.handleRequest(DefaultExtensionProcessor.java:982)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3944)
	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:276)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:931)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1592)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:186)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:452)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:305)
	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:83)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1646)
```
This is because the `java.util.jar.JarFile` extends `ZipFile` that didnt implement the `Closeable` interface back in jdk6 (but it does now). See the [javadoc for ZipFile:jdk6](http://docs.oracle.com/javase/6/docs/api/java/util/zip/ZipFile.html) and [javadoc for ZipFile:jdk8](http://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipFile.html). You probably compile using a jdk8 with compatibility to 6, therefore the code compile on a jdk8 but doesnt work on a jdk6.

I think an easyfix is to close the `JarFile` without using the `IOUtils.closeQuietly` from `commons-io` in `JarWildcardStreamLocator`. The `IOUtils.closeQuietly` method is only a few ligne of code. Let me know if you want a PR.

If you are interested to have a more robust check for jdk6 backward compat, i like the way [spring does it](https://spring.io/blog/2015/04/03/how-spring-achieves-compatibility-with-java-6-7-and-8) with the [animal sniffer plugin](http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/). I have a working pom.xml configuration i could contribute if you are interested.

Thank you !

**Comment by nickho** [comment]
I use the following wro version
```xml
<dependency>
	<groupId>ro.isdc.wro4j</groupId>
	<artifactId>wro4j-core</artifactId>
	<version>1.7.9</version>
</dependency>
```

With this configuration : 
```xml
<groups xmlns="http://www.isdc.ro/wro">

	<!-- load all libraries files -->
	<group name="libs">
		<js>classpath:/META-INF/resources/webjars/jquery/2.2.3/jquery.js</js>
		<js>classpath:/META-INF/resources/webjars/jquery-ui/1.11.4/jquery-ui.js</js>
		<js>classpath:/META-INF/resources/webjars/angularjs/1.5.3/angular.js</js>
		<js>classpath:/META-INF/resources/webjars/angularjs/1.5.3/angular-route.js</js>
		<js>classpath:/META-INF/resources/webjars/angularjs/1.5.3/angular-sanitize.js</js>
		<js>classpath:/META-INF/resources/webjars/angular-ui-utils/0.2.2/ui-utils.js</js>
		<js>classpath:/META-INF/resources/webjars/angular-ui-date/0.0.5/date.js</js>
		<js>classpath:/META-INF/resources/webjars/angular-ui-bootstrap/1.2.5/ui-bootstrap-tpls.js</js>
		<js>classpath:/META-INF/resources/webjars/angular-translate/2.10.0/angular-translate.js</js>
		<js>classpath:/META-INF/resources/webjars/angular-translate-loader-static-files/2.6.1/angular-translate-loader-static-files.js</js>

		<css>classpath:/META-INF/resources/webjars/bootstrap/3.3.6/css/bootstrap.css</css>
		<css>classpath:/META-INF/resources/webjars/bootstrap/3.3.6/css/bootstrap-theme.css</css>
		<css>classpath:/META-INF/resources/webjars/font-awesome/4.5.0/css/font-awesome.css</css>
		<css>classpath:/META-INF/resources/webjars/jquery-ui/1.11.4/jquery-ui.css</css>
		<css>classpath:/META-INF/resources/webjars/jquery-ui/1.11.4/jquery-ui.structure.css</css>
		<css>classpath:/META-INF/resources/webjars/jquery-ui/1.11.4/jquery-ui.theme.css</css>
		<css>classpath:/META-INF/resources/webjars/ajf-skin-am-orange/css/ajf.css</css>
	</group>

	<!-- load all application css and js -->
	<group name="app">
		<js>/app/**.js</js>
		<css>/app/**.css</css>
	</group>

</groups>
```

**Comment by alexo** [comment]
@nickho  thanks for raising this issue. A PR is helpful anytime. Any suggestion or contribution is welcome.
