### ISSUE TITLE
NullPointerException when using wro4j-maven-plugin with ConfigurableWroManagerFactory

### ISSUE THREAD

**Issue by cluick** [wro4j/wro4j#1067]
Dear all,
I use wro4j 1.8.0 to build CSS from LESS and minified JS. Originally I used the wro4j servlet filter to generate the resources on runtime but due to some problems with this approach I want to build the CSS and JS bundles now on compile time. Therefore I configured the wro4j-maven-plugin in my pom.xml with the following configuration:
```
<plugin>
	<groupId>ro.isdc.wro4j</groupId>
	<artifactId>wro4j-maven-plugin</artifactId>
	<version>${wro.version}</version>
	<executions>
		<execution>
			<phase>compile</phase>
			<goals>
				<goal>run</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<destinationFolder>${basedir}/src/main/webapp/dist/</destinationFolder>					
		<contextFolder>${basedir}/src/main/webapp/</contextFolder>
		<wroFile>${basedir}/src/main/webapp/WEB-INF/wro.xml</wroFile>
		<wroManagerFactory>ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory</wroManagerFactory>
		<ignoreMissingResources>false</ignoreMissingResources>
		<targetGroups>main</targetGroups>
	</configuration>
</plugin>
```
When I execute ``mvn compile`` I receive the following error:
```
[INFO] --- wro4j-maven-plugin:1.8.0:run (default) @ maui-web ---
[INFO] C:\Users\cluick\git\maui\maui-web/src/main/webapp/
[INFO] Executing the mojo:
[INFO] Wro4j Model path: C:\Users\cluick\git\maui\maui-web\src\main\webapp\WEB-INF\wro.xml
[INFO] targetGroups: main
[INFO] minimize: true
[INFO] ignoreMissingResources: false
[INFO] parallelProcessing: false
[INFO] buildDirectory: C:\Users\cluick\git\maui\maui-web\target
[INFO] destinationFolder: C:\Users\cluick\git\maui\maui-web\src\main\webapp\dist
[ERROR] Exception occured while processing: ro.isdc.wro.WroRuntimeException, class: ro.isdc.wro.WroRuntimeException,caused by: java.lang.NullPointerException
ro.isdc.wro.WroRuntimeException
        at ro.isdc.wro.WroRuntimeException.wrap(WroRuntimeException.java:69)
        at ro.isdc.wro.WroRuntimeException.wrap(WroRuntimeException.java:54)
        at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.getWroManager(AbstractWro4jMojo.java:458)
        at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.getModel(AbstractWro4jMojo.java:451)
        at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.persistResourceFingerprints(AbstractWro4jMojo.java:311)
        at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.getTargetGroupsAsList(AbstractWro4jMojo.java:298)
        at ro.isdc.wro.maven.plugin.Wro4jMojo.doExecute(Wro4jMojo.java:141)
        at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.execute(AbstractWro4jMojo.java:169)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException
        at ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory.updatePropertiesWithConfiguration(ConfigurableWroManagerFactory.java:186)
        at ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory.access$000(ConfigurableWroManagerFactory.java:45)
        at ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory$1.newProperties(ConfigurableWroManagerFactory.java:84)
        at ro.isdc.wro.model.resource.support.AbstractConfigurableStrategySupport.getProperties(AbstractConfigurableStrategySupport.java:141)
        at ro.isdc.wro.model.resource.support.AbstractConfigurableStrategySupport.getConfiguredValue(AbstractConfigurableStrategySupport.java:55)
        at ro.isdc.wro.model.resource.support.AbstractConfigurableMultipleStrategy.getConfiguredStrategies(AbstractConfigurableMultipleStrategy.java:52)
        at ro.isdc.wro.model.resource.locator.factory.ConfigurableLocatorFactory.newLocatorFactory(ConfigurableLocatorFactory.java:63)
        at ro.isdc.wro.model.resource.locator.factory.ConfigurableLocatorFactory.<init>(ConfigurableLocatorFactory.java:38)
        at ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory$1.<init>(ConfigurableWroManagerFactory.java:80)
        at ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory.newUriLocatorFactory(ConfigurableWroManagerFactory.java:80)
        at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:97)
        at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:74)
        at ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:33)
        at ro.isdc.wro.manager.factory.BaseWroManagerFactory.create(BaseWroManagerFactory.java:160)
        at ro.isdc.wro.manager.factory.BaseWroManagerFactory.create(BaseWroManagerFactory.java:52)
        at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.getWroManager(AbstractWro4jMojo.java:456)
        ... 27 more
[INFO] ------------------
```
The NPE is raised in ``ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory.updatePropertiesWithConfiguration(Properties, String)`` due to a missing java.servlet.FilterConfig. Is it possible to make the ConfiguableWroManagerFactory work during compile time? 

Thank you and best regards,
Christof.

**Comment by cluick** [comment]
Okay, sorry. I´ve used the wrong class name in wroManagerFactory. It should be ``ro.isdc.wro.maven.plugin.manager.factory.ConfigurableWroManagerFactory`` !!! 
I will close this issue.

**Comment by alexo** [comment]
Hi @cluick .
The ConfigurableWroManagerFactory is the default implementation. You don't have to set it explicitly.
