### ISSUE TITLE
Build failure due to failing test in wro4j-maven-plugin

### ISSUE THREAD

**Issue by ppodgorsek** [wro4j/wro4j#1079]
Several tests are failing:

> Tests run: 33, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 9.169 sec <<< FAILURE! - in ro.isdc.wro.maven.plugin.TestWro4jMojo
> testInvalidMojoWithWroManagerFactorySet(ro.isdc.wro.maven.plugin.TestWro4jMojo)  Time elapsed: 0.109 sec  <<< ERROR!
> java.lang.Exception: Unexpected exception, expected<org.apache.maven.plugin.MojoExecutionException> but was<ro.isdc.wro.WroRuntimeException>
> 	at ro.isdc.wro.maven.plugin.TestWro4jMojo.testInvalidMojoWithWroManagerFactorySet(TestWro4jMojo.java:238)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Invalid wroManagerFactoryClass, called: INVALID_CLASS_NAME
> 	at ro.isdc.wro.maven.plugin.TestWro4jMojo.testInvalidMojoWithWroManagerFactorySet(TestWro4jMojo.java:238)
> Caused by: java.lang.ClassNotFoundException: INVALID_CLASS_NAME
> 	at ro.isdc.wro.maven.plugin.TestWro4jMojo.testInvalidMojoWithWroManagerFactorySet(TestWro4jMojo.java:238)
> testMojoWithConfigurableWroManagerFactory(ro.isdc.wro.maven.plugin.TestWro4jMojo)  Time elapsed: 0.114 sec  <<< ERROR!
> java.lang.Exception: Unexpected exception, expected<org.apache.maven.plugin.MojoExecutionException> but was<ro.isdc.wro.WroRuntimeException>
> 	at ro.isdc.wro.maven.plugin.TestWro4jMojo.testMojoWithConfigurableWroManagerFactory(TestWro4jMojo.java:275)
> Caused by: java.lang.NullPointerException
> 	at ro.isdc.wro.maven.plugin.TestWro4jMojo.testMojoWithConfigurableWroManagerFactory(TestWro4jMojo.java:275)

**Comment by ppodgorsek** [comment]
Fixed and merged
