### ISSUE TITLE
Inconsistent types when registering MBean

### ISSUE THREAD

**Issue by ppodgorsek** [wro4j/wro4j#1116]
The configuration getters and setters throw an exception like below upon startup of the WroFilter:

> 2020-11-22 14:06:47,339 ERROR ro.isdc.wro.http.WroFilter.registerMBean - Exception occured while registering MBean
> javax.management.NotCompliantMBeanException: Getter and setter for Debug have inconsistent types
> 	at com.sun.jmx.mbeanserver.MBeanAnalyzer.initMaps(MBeanAnalyzer.java:192) ~[?:?]
> 	at com.sun.jmx.mbeanserver.MBeanAnalyzer.<init>(MBeanAnalyzer.java:118) ~[?:?]
> 	at com.sun.jmx.mbeanserver.MBeanAnalyzer.analyzer(MBeanAnalyzer.java:102) ~[?:?]
> 	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.getAnalyzer(StandardMBeanIntrospector.java:67) ~[?:?]
> 	at com.sun.jmx.mbeanserver.MBeanIntrospector.getPerInterface(MBeanIntrospector.java:192) ~[?:?]
> 	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:138) ~[?:?]
> 	at com.sun.jmx.mbeanserver.StandardMBeanSupport.<init>(StandardMBeanSupport.java:60) ~[?:?]
> 	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:193) ~[?:?]
> 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888) ~[?:?]
> 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320) ~[?:?]
> 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:?]
> 	at ro.isdc.wro.http.WroFilter.registerMBean(WroFilter.java:173) [wro4j-core-1.10.0.jar:1.10.0]
> 	at ro.isdc.wro.http.WroFilter.init(WroFilter.java:120) [wro4j-core-1.10.0.jar:1.10.0]
> 	at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:340) [spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]

**Comment by ppodgorsek** [comment]
Fixed
