### ISSUE TITLE
CSS URL rewriting fails when Bootstrap is in a WebJar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#748]
When I put bootstrap.css in src/main/resources and use the classpath locator, it works:

```
<css>classpath:bootstrap/2.3.2/css/bootstrap.css</css>
```

But with the Bootstrap WebJar, I get the following error:

```
<css>webjar:bootstrap.css</css>
```

Exception occured while processing: ro.isdc.wro.WroRuntimeException:
Could not replace imageUrl: ../img/glyphicons-halflings.png, contained at location: webjar:bootstrap.css, class: ro.isdc.wro.WroRuntimeException,caused by:  (ro.isdc.wro4j:wro4j-maven-plugin:1.7.0:run:default:compile)
pom.xml /radar-webapp   line 62 Maven Build Problem

**Note**: issue migrated from https://github.com/alexo/wro4j/issues/127

**Comment by alexo** [comment]
There is a workaround for this problem: 
instead of using webjar uri, it is possible to use webjar servlet & add serlet context relative resources to wro.xml.

More details about webjars servlet can be found here: http://www.webjars.org/documentation

**Comment by hantsy** [comment]
@alexo 

I used wro maven plugin in my projects, I did not include webjars files in the final deployments, the webjars  are just dependencies of the wro maven plugin. After it is processed, the new css and js is generated for the project, no need webjars in future.

When wro is processing the webjars resources, it is possible to an option to copy the static resources(such as fonts, images) in the webjars to my own project location? Generally, it could be /fonts, /images etc. Do not replace the uri in the css, js files of webjars.

**Comment by alexo** [comment]
Though it is not possible out of the box, I believe there are plugins which allow you to just copy resources from a jar to any custom location. Another approach for this problem, is to keep webjars in your build (typically a war file) and expose a [servlet](https://github.com/webjars/webjars-servlet-2.x) which access the webjar resources easily as if they would be a simple static resources. 

I've done some progress on this side, which should be available in next release (1.8.0). There is also an [example project](https://github.com/wro4j/wro4j-examples/tree/master/wro4j-bootstrap-buildtime) which uses this idea.

Let me know what do you think about it.

**Comment by hantsy** [comment]
@alexo  Thanks. 
In my project I do not use webjars in final deployment. I used webjars: prefix in wro config, and copy the fonts in bootstrap webjars jar to my project manually.

https://github.com/hantsy/angularjs-springmvc-sample

**Comment by alexo** [comment]
The advantage of using webjars-servlet, is that you don't have to specify the version of resources.

**Comment by hantsy** [comment]
I understand your meaning, Spring 4.2 also includes similar features.

But the disadvantage is some webjars includes too many source files which is no use in our projects.

**Comment by alexo** [comment]
I understand your concern. In the end - there is a trade-off between how fat is your deployed app vs how easy is to configure which resources should be copied. 
From my point of view, a typical webapp has a large amount of dependencies anyway and it doesn't always worth excluding webjars, since it won't change the overall size dramatically. 

I'm pretty sure, you could find a maven plugin which copies files from dependencies to a predefined location if not including webjars in final deployment artifact is an issue for you.

**Comment by hantsy** [comment]
@alexo  thanks for your help. I will try webjars url later. Of course, I am more care about which way is easy.

**Comment by hajderr** [comment]
Hello

I'm not sure if there's been any progress. What's the conclusion about this? I'm doing using `wro4j-maven-plugin` and got the following setup, nothing unusual what I think. I noticed that I got the same error as the original question with NullPointerException. However, cleaning up the wro.properties (both version pasted below) it worked.
```
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro">
  <group name="angular-bootstrap">
      <group-ref>bootstrap</group-ref>
      <group-ref>angular</group-ref>
  </group>
    <group name="bootstrap">      
        <js>/webjars/jquery/2.1.1/jquery.min.js</js>
        <js>/webjars/bootstrap/3.3.6/bootstrap.js</js>      
    </group>
    <group name="angular">
        <js>/webjars/angularjs/1.3.8/angular.min.js</js>
        <js>/webjars/angularjs/1.3.8/angular-route.min.js</js>
    </group>
</groups>
```

wro.properties faulty
===

```
modelUpdatePeriod=5
resourceWatcherUpdatePeriod=5
debug=true
gzipResources=true
cacheGzippedContent=false
ignoreMissingResources=false
jmxEnabled=true
parallelPreprocessing=false
managerFactoryClassName=ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory
preProcessors=cssUrlRewriting,cssImport,semicolonAppender
postProcessors=cssMinJawr,googleClosureSimple

uriLocators=servletContext.DISPATCHER_FIRST,uri,classpath
ignoreEmptyGroup=false
ignoreFailingProcessor=false
hashStrategy=MD5
```

wro.properties OK
===


```
preProcessors=cssUrlRewriting,cssImport,semicolonAppender
postProcessors=cssMinJawr,googleClosureSimple
```
Can someone more experienced please spot what would cause the error? I think the faulty one is from one sample project in wro4j-examples.

Let me know if I can contribute. I've downloaded the repo and I'm read to assist.

**Comment by alexo** [comment]
What exactly is the difference between those two properties ? It seem that processors are exactly the same...

Try running maven plugin with -X option (debug) and provide a detailed stacktrace of the thrown exception.

**Comment by hajderr** [comment]
That's exactly my point. I'm not sure if you can see. I'm pasting the stack trace, and attaching a file with more output.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.853 s
[INFO] Finished at: 2016-05-27T18:08:54+01:00
[INFO] Final Memory: 26M/380M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project api: Exception occured while processing: ro.isdc.wro.WroRuntimeException: Exception while merging resources: Could not locate uri: /webjars/angularjs/1.3.8/angular.min.js, class: ro.isdc.wro.WroRuntimeException,caused by: java.io.IOException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project api: Exception occured while processing: ro.isdc.wro.WroRuntimeException: Exception while merging resources: Could not locate uri: /webjars/angularjs/1.3.8/angular.min.js, class: ro.isdc.wro.WroRuntimeException,caused by: java.io.IOException
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception occured while processing: ro.isdc.wro.WroRuntimeException: Exception while merging resources: Could not locate uri: /webjars/angularjs/1.3.8/angular.min.js, class: ro.isdc.wro.WroRuntimeException,caused by: java.io.IOException
	at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.execute(AbstractWro4jMojo.java:179)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: ro.isdc.wro.WroRuntimeException: Exception while merging resources: Could not locate uri: /webjars/angularjs/1.3.8/angular.min.js
	at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:86)
	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
	at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
	at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
	at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
	at ro.isdc.wro.maven.plugin.Wro4jMojo.processGroup(Wro4jMojo.java:277)
	at ro.isdc.wro.maven.plugin.Wro4jMojo.doExecute(Wro4jMojo.java:161)
	at ro.isdc.wro.maven.plugin.AbstractWro4jMojo.execute(AbstractWro4jMojo.java:169)
	... 21 more
Caused by: java.io.IOException: Could not locate uri: /webjars/angularjs/1.3.8/angular.min.js
	at ro.isdc.wro.model.resource.locator.ServletContextUriLocator.servletContextBasedStreamLocator(ServletContextUriLocator.java:226)
	at ro.isdc.wro.model.resource.locator.ServletContextUriLocator.dispatcherFirstStreamLocator(ServletContextUriLocator.java:202)
	at ro.isdc.wro.model.resource.locator.ServletContextUriLocator.locate(ServletContextUriLocator.java:169)
	at ro.isdc.wro.model.resource.locator.factory.InjectableUriLocatorFactoryDecorator.locate(InjectableUriLocatorFactoryDecorator.java:42)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.getResourceContent(PreProcessorExecutor.java:249)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.applyPreProcessors(PreProcessorExecutor.java:189)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:103)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:77)
	at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:83)
	... 29 more
Caused by: java.lang.NullPointerException
	at ro.isdc.wro.model.resource.locator.ServletContextUriLocator.servletContextBasedStreamLocator(ServletContextUriLocator.java:224)
	... 37 more
```
[builderror.txt](https://github.com/wro4j/wro4j/files/286932/builderror.txt)

**Comment by alexo** [comment]
Since you include webjar resources, you should be using webjar locator. I believe the exception is thrown because the configured locators are unable to locate resources

**Comment by hajderr** [comment]
I tried
`webjar:/angularjs....
`and
`webjar:angularjs... (no slash)
`
but still same exception. Switching to the lighter properties file, the exception is then about rewriting of the glyphicons (relative path). 

`[ERROR] Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project api: Exception occured while processing: ro.isdc.wro.WroRuntimeException: Could not replace imageUrl: ../fonts/glyphicons-halflings-regular.eot, contained at location: webjar:/bootstrap/3.3.6/css/bootstrap.css, class: ro.isdc.wro.WroRuntimeException,caused by: -> [Help 1]`

**Comment by alexo** [comment]
Use locator called "webjar" (instead of "webjars") and use the following path when including webjar resources:

`/webjar/angularjs.....`

The WebjarLocator (similar to WebjarsLocator) uses a path similar to ServletContextLocator and is preferred to the older locator.

**Comment by alexo** [comment]
@hajderr the configuration from your example is missing webjars uriLocator.
Also, it would be easier to understand or fix a problem if there would be an example available as a public github repo.
