### ISSUE TITLE
Delta check fails if project directory contains ","

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#901]
```
I had the strange error that, though there were no hashes saved in 
"build.properties", no css files were generated. After some debugging I found 
that an exception was logged in ResourceChangeHandler. Unfortunately this error 
was logged in level debug. I created #206 to change this.

After looking at the exception I quickly found the error: My project directory 
contains ",". This is because the job in Jenkins is named like this: "Deploy 
webapp to preview, staging, live". This string is then splitted and produces 
this error:

[ERROR] failed to check for delta resource: 
ro.isdc.wro.model.resource.Resource@fabb651[CSS,/scss/print.scss,true].
java.io.IOException: No valid resource '/scss/print.scss' found inside any of 
contextFolders: [/data/jenkins/workspace/Deploy webapp to preview, staging, 
live]
        at ro.isdc.wro.model.resource.locator.StandaloneServletContextUriLocator.locate(StandaloneServletContextUriLocator.java:57)
        at ro.isdc.wro.model.resource.locator.factory.InjectableUriLocatorFactoryDecorator.locate(InjectableUriLocatorFactoryDecorator.java:37)
        at ro.isdc.wro.maven.plugin.support.ResourceChangeHandler.isResourceChanged(ResourceChangeHandler.java


 At least outputting the exception on level error would help others to see that there is something wrong.

References:
https://github.com/alexo/wro4j/issues/207
```

Original issue reported on code.google.com by `alex.obj...@gmail.com` on 16 Sep 2014 at 8:21

**Comment by alexo** [comment]
The error log level was changed from debug to error. No other changes applied.
