### ISSUE TITLE
NPE during parallel initialization of WRO handler

### ISSUE THREAD

**Issue by sodik82** [wro4j/wro4j#961]
I have encountered following NPE after server restart (basically the same exception for 3 different threads at roughly same time):

```
14:20:21.555 [http-nio-8080-exec-6] ERROR ro.isdc.wro.http.WroFilter - Exception occured
java.lang.NullPointerException: null
	at ro.isdc.wro.http.handler.LazyRequestHandlerDecorator$1.initialize(LazyRequestHandlerDecorator.java:33) ~[wro4j-core-1.7.8.jar:1.7.8]
	at ro.isdc.wro.http.handler.LazyRequestHandlerDecorator$1.initialize(LazyRequestHandlerDecorator.java:27) ~[wro4j-core-1.7.8.jar:1.7.8]
	at ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:33) ~[wro4j-core-1.7.8.jar:1.7.8]
	at ro.isdc.wro.http.handler.LazyRequestHandlerDecorator.getRequestHandler(LazyRequestHandlerDecorator.java:61) ~[wro4j-core-1.7.8.jar:1.7.8]
	at ro.isdc.wro.http.handler.LazyRequestHandlerDecorator.isEnabled(LazyRequestHandlerDecorator.java:54) ~[wro4j-core-1.7.8.jar:1.7.8]
	at ro.isdc.wro.http.WroFilter.handledWithRequestHandler(WroFilter.java:312) ~[wro4j-core-1.7.8.jar:1.7.8]
	at ro.isdc.wro.http.WroFilter.doFilter(WroFilter.java:288) ~[wro4j-core-1.7.8.jar:1.7.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.59.jar:7.0.59]

```

Afterwards the web page was not rendered correctly (due to missing CSS etc).

Btw: Similar exception I have found here https://travis-ci.org/alexo/wro4j/builds/56631459

**Comment by alexo** [comment]
Thanks for reporting this issue.

**Comment by anuja-dalal** [comment]
Facing same problem. Is this scheduled to be released in near future?

**Comment by alexo** [comment]
It is fixed on a feature branch. Will soon be merged and released.
