### ISSUE TITLE
wro4j-runner 1.7.7 jshint fails with Exception in thread "main" java.lang.NoClassDefFoundError: groovy/lang/GroovyShell

### ISSUE THREAD

**Issue by broctany** [wro4j/wro4j#965]
Does jshint processor require the groovy libs? Should I add them to the classpath? When I use ant to run it I can't get pass this error:
```
jshint:
     [exec] processing group: @{targetgroups}.css
     [exec] Processing took: 740ms
     [exec] Exception in thread "main" java.lang.NoClassDefFoundError: groovy/lang/GroovyShell
     [exec]     at ro.isdc.wro.extensions.model.factory.GroovyModelFactory.create(GroovyModelFactory.java:64)
     [exec]     at ro.isdc.wro.extensions.model.factory.GroovyModelFactory.create(GroovyModelFactory.java:42)
     [exec]     at ro.isdc.wro.model.factory.LazyWroModelFactoryDecorator.create(LazyWroModelFactoryDecorator.java:28)
     [exec]     at ro.isdc.wro.model.factory.LazyWroModelFactoryDecorator.create(LazyWroModelFactoryDecorator.java:16)
     [exec]     at ro.isdc.wro.extensions.model.factory.SmartWroModelFactory.create(SmartWroModelFactory.java:194)
     [exec]     at ro.isdc.wro.extensions.model.factory.SmartWroModelFactory.create(SmartWroModelFactory.java:38)
     [exec]     at ro.isdc.wro.model.factory.WroModelFactoryDecorator.create(WroModelFactoryDecorator.java:27)
     [exec]     at ro.isdc.wro.model.factory.FallbackAwareWroModelFactory.create(FallbackAwareWroModelFactory.java:48)
     [exec]     at ro.isdc.wro.model.factory.FallbackAwareWroModelFactory.create(FallbackAwareWroModelFactory.java:22)
     [exec]     at ro.isdc.wro.model.factory.WroModelFactoryDecorator.create(WroModelFactoryDecorator.java:27)
     [exec]     at ro.isdc.wro.model.factory.ModelTransformerFactory.create(ModelTransformerFactory.java:55)
     [exec]     at ro.isdc.wro.model.factory.ModelTransformerFactory.create(ModelTransformerFactory.java:27)
     [exec]     at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator$1.initialize(DefaultWroModelFactoryDecorator.java:60)
     [exec]     at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator$1.initialize(DefaultWroModelFactoryDecorator.java:50)
     [exec]     at ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:33)
     [exec]     at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator.create(DefaultWroModelFactoryDecorator.java:114)
     [exec]     at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator.create(DefaultWroModelFactoryDecorator.java:35)
     [exec]     at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:71)
     [exec]     at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
     [exec]     at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
     [exec]     at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
     [exec]     at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
     [exec]     at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.doProcess(Wro4jCommandLineRunner.java:278)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.processGroup(Wro4jCommandLineRunner.java:220)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.process(Wro4jCommandLineRunner.java:187)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.doMain(Wro4jCommandLineRunner.java:152)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.main(Wro4jCommandLineRunner.java:104)
     [exec] Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyShell
     [exec]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
     [exec]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
     [exec]     at java.security.AccessController.doPrivileged(Native Method)
     [exec]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
     [exec]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
     [exec]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
     [exec]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [exec]     ... 28 more
```

**Comment by alexo** [comment]
It shouldn't require groovy dependency. 
Btw, the latest version is 1.7.8.

**Comment by broctany** [comment]
Thanks for the response. I fiddled a bit and found that groovy-all jar and Google's gson jar are needed to run 1.7.7 in ant; basically I need to specify ro.isdc.wro.runner.Wro4jCommandLineRunner as the main class and explicitly add the above 2 jars together with the 1.7.7 jar on the classpath, which makes jshint run normally. I'll try out 1.7.8 though (this may be a dumb question, but where is the official place to download wro4j runner jars? I got them here: https://drive.google.com/folderview?id=0Bw_8FNG2SipAT2VHOHlHbW9WLUE&usp=sharing, but it has only up to 1.7.7)

**Comment by alexo** [comment]
@broctany indeed, the 1.7.8 version is missing from google drive folder. The runner is not published on maven central repo. I usually build it after each release and upload it to google drive (will do it later). You can build it yourself anytime, just update the wro4j.version to latest version.

**Comment by broctany** [comment]
@alexo Great, thank you!

**Comment by broctany** [comment]
After building the latest 1.7.8, I found this gson related issue when running jshint from command line:
```
jshint:
     [exec] processing group: common.css
     [exec] processing group: common.js
     [exec] Processing took: 9306ms
     [exec] Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/reflect/TypeToken
     [exec]     at java.lang.ClassLoader.defineClass1(Native Method)
     [exec]     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
     [exec]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [exec]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
     [exec]     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
     [exec]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
     [exec]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
     [exec]     at java.security.AccessController.doPrivileged(Native Method)
     [exec]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
     [exec]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
     [exec]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
     [exec]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [exec]     at ro.isdc.wro.extensions.processor.support.linter.AbstractLinter.validate(AbstractLinter.java:100)
     [exec]     at ro.isdc.wro.extensions.processor.js.AbstractLinterProcessor.process(AbstractLinterProcessor.java:66)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.SupportAwareProcessorDecorator.process(SupportAwareProcessorDecorator.java:39)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.ExceptionHandlingProcessorDecorator.process(ExceptionHandlingProcessorDecorator.java:56)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.BenchmarkProcessorDecorator.process(BenchmarkProcessorDecorator.java:44)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec]     at ro.isdc.wro.model.resource.processor.decorator.DefaultProcessorDecorator.process(DefaultProcessorDecorator.java:42)
     [exec]     at ro.isdc.wro.model.group.processor.PreProcessorExecutor$2.process(PreProcessorExecutor.java:228)
     [exec]     at ro.isdc.wro.model.group.processor.PreProcessorExecutor.applyPreProcessors(PreProcessorExecutor.java:207)
     [exec]     at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:103)
     [exec]     at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:77)
     [exec]     at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:83)
     [exec]     at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
     [exec]     at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
     [exec]     at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
     [exec]     at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
     [exec]     at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.doProcess(Wro4jCommandLineRunner.java:278)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.processGroup(Wro4jCommandLineRunner.java:220)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.process(Wro4jCommandLineRunner.java:187)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.doMain(Wro4jCommandLineRunner.java:152)
     [exec]     at ro.isdc.wro.runner.Wro4jCommandLineRunner.main(Wro4jCommandLineRunner.java:104)
     [exec] Caused by: java.lang.ClassNotFoundException: com.google.gson.reflect.TypeToken
     [exec]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
     [exec]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
     [exec]     at java.security.AccessController.doPrivileged(Native Method)
     [exec]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
     [exec]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
     [exec]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
     [exec]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [exec]     ... 39 more
```
I changed the gson library scope from "provided" to "compile" in wro4j-runner's pom.xml and it works fine.
