### ISSUE TITLE
Stale wro4j-core.jar when undeployed on windows tomcat

### ISSUE THREAD

**Issue by tombueng** [wro4j/wro4j#980]
My application cannot be undeployed correctly on windows tomcat because there seems to be a file-lock on the wro4j-core.....jar event after application shutdown.

I tried to manually call WroManagerFactory.destroy() without any luck.

I suspect wro4j itself causing this file to be locked.
How do I correctly shutdown wro4j correctly?

**Comment by tombueng** [comment]
We configure the wro4jFilter over Spring. And use the ro.isdc.wro.http.ConfigurableWroFilter in conjunction with the ro.isdc.wro.manager.factory.BaseWroManagerFactory.

<filter>
		<filter-name>webResourceOptimizer</filter-name>
		<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
		
		<init-param>
			<param-name>targetBeanName</param-name>
			<param-value>wro4jFilter</param-value>
		</init-param>
		<init-param>
			<param-name>targetFilterLifecycle</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>

**Comment by tombueng** [comment]
I used http://file-leak-detector.kohsuke.org/ do find open file-locks on the wro4j-core.jar.
This is what I found out:

#33 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:http-bio-8080-exec-5 on Thu Oct 01 13:57:36 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.catalina.loader.WebappClassLoader.findLoadedResource(WebappClassLoader.java:3296)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1469)
	at java.lang.Class.getResourceAsStream(Class.java:2210)
	at ro.isdc.wro.util.WroUtil.loadRegexpWithKey(WroUtil.java:322)
	at ro.isdc.wro.model.resource.processor.impl.js.SemicolonAppenderPreProcessor.<clinit>(SemicolonAppenderPreProcessor.java:33)
	at ro.isdc.wro.model.resource.processor.factory.DefaultProcessorsFactory.<init>(DefaultProcessorsFactory.java:27)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory.newProcessorsFactory(BaseWroManagerFactory.java:203)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:94)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:74)
	...
	
	
#51 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:http-bio-8080-exec-5 on Thu Oct 01 13:57:36 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.catalina.loader.WebappClassLoader.findLoadedResource(WebappClassLoader.java:3296)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1469)
	at java.lang.Class.getResourceAsStream(Class.java:2210)
	at ro.isdc.wro.util.WroUtil.loadRegexpWithKey(WroUtil.java:322)
	at ro.isdc.wro.model.resource.processor.impl.css.CssVariablesProcessor.<clinit>(CssVariablesProcessor.java:51)
	at ro.isdc.wro.model.resource.processor.factory.DefaultProcessorsFactory.<init>(DefaultProcessorsFactory.java:30)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory.newProcessorsFactory(BaseWroManagerFactory.java:203)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:94)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:74)
	...
	
	
#54 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:http-bio-8080-exec-5 on Thu Oct 01 13:57:36 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.catalina.loader.WebappClassLoader.findLoadedResource(WebappClassLoader.java:3296)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1469)
	at java.lang.Class.getResourceAsStream(Class.java:2210)
	at ro.isdc.wro.util.WroUtil.loadRegexpWithKey(WroUtil.java:322)
	at ro.isdc.wro.model.resource.processor.impl.css.CssVariablesProcessor.<clinit>(CssVariablesProcessor.java:43)
	at ro.isdc.wro.model.resource.processor.factory.DefaultProcessorsFactory.<init>(DefaultProcessorsFactory.java:30)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory.newProcessorsFactory(BaseWroManagerFactory.java:203)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:94)
	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:74)
	...
	
	
#65 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:http-bio-8080-exec-5 on Thu Oct 01 13:57:36 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.catalina.loader.WebappClassLoader.findLoadedResource(WebappClassLoader.java:3296)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1469)
	at java.lang.Class.getResourceAsStream(Class.java:2210)
	at ro.isdc.wro.util.WroUtil.loadRegexpWithKey(WroUtil.java:322)
	at ro.isdc.wro.model.resource.processor.impl.css.CssVariablesProcessor.<clinit>(CssVariablesProcessor.java:47)
	at ro.isdc.wro.model.resource.processor.factory.DefaultProcessorsFactory.<init>(DefaultProcessorsFactory.java:30)	
	...
	
	
#78 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:localhost-startStop-1 on Thu Oct 01 13:57:24 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.catalina.loader.WebappClassLoader.findLoadedResource(WebappClassLoader.java:3296)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1469)
	at java.lang.Class.getResourceAsStream(Class.java:2210)
	at ro.isdc.wro.util.WroUtil.loadRegexpWithKey(WroUtil.java:322)
	at ro.isdc.wro.util.WroUtil.<clinit>(WroUtil.java:64)
	at ro.isdc.wro.http.WroFilter.init(WroFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:326)
	at org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java:235)
	at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:199)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	...

#82 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:localhost-startStop-1 on Thu Oct 01 13:57:24 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.catalina.loader.WebappClassLoader.findLoadedResource(WebappClassLoader.java:3296)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1469)
	at java.lang.Class.getResourceAsStream(Class.java:2210)
	at ro.isdc.wro.util.WroUtil.loadRegexpWithKey(WroUtil.java:322)
	at ro.isdc.wro.util.WroUtil.<clinit>(WroUtil.java:63)
	at ro.isdc.wro.http.WroFilter.init(WroFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:326)
	at org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java:235)
	at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:199)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	...

#119 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:localhost-startStop-1 on Thu Oct 01 13:57:24 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.catalina.loader.WebappClassLoader.findLoadedResource(WebappClassLoader.java:3296)
	at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1500)
	at java.lang.Class.getResourceAsStream(Class.java:2210)
	at ro.isdc.wro.util.WroUtil.loadRegexpWithKey(WroUtil.java:322)
	at ro.isdc.wro.util.WroUtil.<clinit>(WroUtil.java:53)
	at ro.isdc.wro.http.WroFilter.init(WroFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:326)
	at org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java:235)
	at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:199)
	...


#125 C:\_ws\insign-trunk\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\insign-webapp\WEB-INF\lib\wro4j-core-1.7.8.jar by thread:http-bio-8080-exec-3 on Thu Oct 01 13:57:35 CEST 2015
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.apache.catalina.loader.WebappClassLoader.openJARs(WebappClassLoader.java:2818)
	at org.apache.catalina.loader.WebappClassLoader.findResourceInternal(WebappClassLoader.java:3071)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2853)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1174)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1669)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at org.springframework.web.context.request.RequestContextListener.requestInitialized(RequestContextListener.java:59)
	at org.apache.catalina.core.StandardContext.fireRequestInitEvent(StandardContext.java:6103)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:167)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	...

**Comment by tombueng** [comment]
I suppose this is one of the bugs: WroUtil.loadRegexpWithKey won't close the input-stream

**Comment by alexo** [comment]
Thanks for reporting the issue. If you have found the root cause and are willing to contribute, I would really appreciate it ;)

**Comment by tombueng** [comment]
I will J

 

Von: Alex Objelean [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. Oktober 2015 14:24
An: wro4j/wro4j
Cc: tombueng
Betreff: Re: [wro4j] Stale wro4j-core.jar when undeployed on windows tomcat (#980)

 

Thanks for reporting the issue. If you have found the root cause and are willing to contribute, I would really appreciate it ;)

**Comment by tombueng** [comment]
Closing the stream in WroUtil.loadRegexpWithKey will fix the issue.
