### ISSUE TITLE
NPE randomly during build

### ISSUE THREAD

**Issue by busches** [wro4j/wro4j#992]
We're currently on version 1.7.7 and we have multiple teams building the same project on their respective Jenkins boxes and only a few of them are seeing the following NPE when running the Ant task. 

```
processing group: ie-polyfill.css
processing group: ie-polyfill.js
null
java.lang.NullPointerException
	at ro.isdc.wro.model.resource.processor.decorator.ExceptionHandlingProcessorDecorator.isIgnoreFailingProcessor(ExceptionHandlingProcessorDecorator.java:80)
	at ro.isdc.wro.model.resource.processor.decorator.ExceptionHandlingProcessorDecorator.process(ExceptionHandlingProcessorDecorator.java:60)
	at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:89)
	at ro.isdc.wro.model.resource.processor.decorator.BenchmarkProcessorDecorator.process(BenchmarkProcessorDecorator.java:44)
	at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:89)
	at ro.isdc.wro.model.resource.processor.decorator.DefaultProcessorDecorator.process(DefaultProcessorDecorator.java:42)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor$2.process(PreProcessorExecutor.java:228)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.applyPreProcessors(PreProcessorExecutor.java:207)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:103)
	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:77)
	at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:83)
	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
	at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
	at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
	at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
	at ro.isdc.wro.runner.Wro4jCommandLineRunner.doProcess(Wro4jCommandLineRunner.java:278)
	at ro.isdc.wro.runner.Wro4jCommandLineRunner.processGroup(Wro4jCommandLineRunner.java:220)
	at ro.isdc.wro.runner.Wro4jCommandLineRunner.process(Wro4jCommandLineRunner.java:187)
	at ro.isdc.wro.runner.Wro4jCommandLineRunner.doMain(Wro4jCommandLineRunner.java:152)
	at ro.isdc.wro.runner.Wro4jCommandLineRunner.main(Wro4jCommandLineRunner.java:104)
null
```

The error seems to occur primarily during longer jobs, 30 minutes or longer, and isn't 100% reproducible, as if we ran the job again it normally passes. The only thing that's consistent is it always seems to fail after processing a group, but almost always a different group. The job is the only job executing on the box when it fails and when it passes.

Let me know if there's other information I can provide, but it's very random. Of the seven jobs I have in history on the one server, three failed and four passed, going P, F, P, F, F, P, P.

**Comment by alexo** [comment]
This should be fixed in this issue: https://github.com/wro4j/wro4j/issues/961 which was released as part of release 1.7.9.

**Comment by alexo** [comment]
Closing issue as duplicate of #961. Feel free to reopen if you can reproduce it in latest version.

**Comment by busches** [comment]
I did see that issue, but we have `parallelPreprocessing` set to `false`, so I wasn't sure if it still applied. 

Here is our configuration file:
```
debug=true
minimizeEnabled=true
gzipResources=true
resourceWatcherUpdatePeriod=1000
resourceWatcherAsync=false
cacheUpdatePeriod=1000
modelUpdatePeriod=1000
parallelPreprocessing=false
connectionTimeout=2000
encoding=UTF-8
ignoreMissingResources=false
ignoreEmptyGroup=true
ignoreFailingProcessor=false
cacheGzippedContent=true
jmxEnabled=false
preProcessors=cssMinJawr,cssUrlRewriting,jsMin,semicolonAppende
uriLocators=servletContext,uri,classpath
```

**Comment by alexo** [comment]
@busches could you upgrade to 1.7.9 and reopen this issue if the exception is still reproducible?

**Comment by busches** [comment]
We're using wro4j-runner, sorry for not stating that sooner, and the latest version I see is 1.7.7 - https://github.com/wro4j/wro4j-runner/releases

**Comment by alexo** [comment]
You can build it yourself using steps described here: https://github.com/wro4j/wro4j-runner

**Comment by busches** [comment]
I'll give that a whirl. For other users, is there a reason the runner isn't updated in sync with wro4j releases?

**Comment by busches** [comment]
Building it with Java 6 still gives me an error saying it needs Java 7. Was one of the dependencies upgraded and broke Java 6? I didn't see that in the release notes.

```
     [exec] Exception in thread "main" java.lang.UnsupportedClassVersionError: org/webjars/WebJarAssetLocator : Unsupported major.minor version 51.0
     [exec] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [exec] 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
     [exec] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
     [exec] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
     [exec] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
     [exec] 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
     [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
     [exec] 	at ro.isdc.wro.extensions.locator.WebjarUriLocator.newWebJarAssetLocator(WebjarUriLocator.java:50)
     [exec] 	at ro.isdc.wro.extensions.locator.WebjarUriLocator.<init>(WebjarUriLocator.java:42)
     [exec] 	at ro.isdc.wro.extensions.locator.support.DefaultLocatorProvider.provideLocators(DefaultLocatorProvider.java:27)
     [exec] 	at ro.isdc.wro.extensions.support.spi.DefaultConfigurableProvider.provideLocators(DefaultConfigurableProvider.java:72)
     [exec] 	at ro.isdc.wro.model.resource.locator.factory.DefaultUriLocatorFactory.<init>(DefaultUriLocatorFactory.java:23)
     [exec] 	at ro.isdc.wro.manager.WroManager$Builder.<init>(WroManager.java:333)
     [exec] 	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:77)
     [exec] 	at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:74)
     [exec] 	at ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:33)
     [exec] 	at ro.isdc.wro.manager.factory.BaseWroManagerFactory.create(BaseWroManagerFactory.java:160)
     [exec] 	at ro.isdc.wro.manager.factory.BaseWroManagerFactory.create(BaseWroManagerFactory.java:52)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.getTargetGroupsAsList(Wro4jCommandLineRunner.java:201)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.process(Wro4jCommandLineRunner.java:183)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.doMain(Wro4jCommandLineRunner.java:152)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.main(Wro4jCommandLineRunner.java:104)
```

**Comment by alexo** [comment]
Apparently one of transitive dependency require java 7. Is that a problem for you?

I was not keeping it in sync mostly because I wasn't sure it is being used. Also, it is quite easy to do. Will build it tomorrow ... :)

**Comment by busches** [comment]
Yes, our application is still on Java 6 sadly.

**Comment by alexo** [comment]
@busches you could try using a different version of dependencies which require java 7 (downgrade them). For this particular case, use an older version of webjars-locator which is built with jdk 6. This would mean that you need to build a custom version of wro4j-runner. I could help you with that if you have problem.

**Comment by busches** [comment]
That would be great to know, one of the builds is failing 75% of the time.

**Comment by alexo** [comment]
@busches we could chat here: https://gitter.im/wro4j/wro4j

**Comment by busches** [comment]
Upgrading to 1.7.9 has given us 4 clean builds, but we just ran into this again:

```
[exec] java.lang.NullPointerException
     [exec] 	at ro.isdc.wro.model.resource.processor.decorator.ExceptionHandlingProcessorDecorator.isIgnoreFailingProcessor(ExceptionHandlingProcessorDecorator.java:80)
     [exec] 	at ro.isdc.wro.model.resource.processor.decorator.ExceptionHandlingProcessorDecorator.process(ExceptionHandlingProcessorDecorator.java:60)
     [exec] 	at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec] 	at ro.isdc.wro.model.resource.processor.decorator.BenchmarkProcessorDecorator.process(BenchmarkProcessorDecorator.java:44)
     [exec] 	at ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator.process(ProcessorDecorator.java:86)
     [exec] 	at ro.isdc.wro.model.resource.processor.decorator.DefaultProcessorDecorator.process(DefaultProcessorDecorator.java:42)
     [exec] 	at ro.isdc.wro.model.group.processor.PreProcessorExecutor$2.process(PreProcessorExecutor.java:228)
     [exec] 	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.applyPreProcessors(PreProcessorExecutor.java:207)
     [exec] 	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:103)
     [exec] 	at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:77)
     [exec] 	at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:83)
     [exec] 	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
     [exec] 	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
     [exec] 	at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
     [exec] 	at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
     [exec] 	at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.doProcess(Wro4jCommandLineRunner.java:278)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.processGroup(Wro4jCommandLineRunner.java:220)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.process(Wro4jCommandLineRunner.java:187)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.doMain(Wro4jCommandLineRunner.java:152)
     [exec] 	at ro.isdc.wro.runner.Wro4jCommandLineRunner.main(Wro4jCommandLineRunner.java:104)
     [exec] null
```

**Comment by alexo** [comment]
Ok, so I was wrong. This problem was not fixed. 
Reopening it.

**Comment by busches** [comment]
As an update, we've removed the `jsMin` and `uglifyJs` processors from our build and have not had a build failure in over 20 builds. This leaves us with just `cssMinJawr`, `cssUrlRewriting`, and `semicolonAppender` for processors.

**Comment by alexo** [comment]
We could assume that jsMin or uglifyJs causes the problem. Could try removing only one of them and confirm which one is the real problem (or both of them)?

**Comment by busches** [comment]
@alexo We did try removing one at a time and had failures whenever one of them was enabled. Only with both of them disabled are we seeing the long streak.

**Comment by alexo** [comment]
ok, thanks for the info. That narrows down the problem.
