### ISSUE TITLE
SASS locator problems

### ISSUE THREAD

**Issue by magnyld** [wro4j/wro4j#993]
Hi

I try to reuse the RubySassCssProcessor, like here, http://wro4j.readthedocs.org/en/stable/ReusingProcessors/,  but is unable to configure the paths correctly when I have an import in my sass file. http://wro4j.readthedocs.org/en/stable/ReusingProcessors/

This is my code:

        String file = "/_dsf/contrib/js/foundation-5.5.3/scss/foundation.scss";
        Resource resource = Resource.create("foundation.scss", ResourceType.CSS);
        File f = new File(request.getServletContext().getRealPath(file));

        // Create the configuration object and use it for current context
        WroConfiguration config = new WroConfiguration();
        Context.set(Context.standaloneContext(), config);
        try {
            // Create injector which will inject all dependencies of the
            // processor
            Injector injector = new InjectorBuilder().build();

            RubySassCssProcessor processor = new RubySassCssProcessor();

            // this will inject all required fields, after this point it is safe
            // to use processor outside of wro4j context.
            injector.inject(processor);

            // Do the actual processing

            processor.process(resource, new FileReader(f), writer);
     
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            Context.unset();
        }

This is the error I get from the processor

Sass::SyntaxError: File to import not found or unreadable: foundation/components/grid.
Load path: /Users/andreas/eclipse/jee-mars/Eclipse.app/Contents/MacOS

How do you configure the paths/locators? I dont see it anywhere in the source of the processor?

Best regards Andreas

**Comment by magnyld** [comment]
Hi again, 

Found this, is this something that will come in an upcoming release any time soon?

https://code.google.com/p/wro4j/issues/detail?id=888

**Comment by alexo** [comment]
@magnyld the issue was migrated to github. It is now located here: https://github.com/wro4j/wro4j/issues/888
It is not in progress yet. I'd be more than happy if anyone would start working on it.

**Comment by alexo** [comment]
Regarding the locator issue. It is possible to set UriLocatorFactory on InjectorBuilder, but I'm not yet sure it would help, since the rubySassProcessor has its own mechanism for retrieving relative resources. 
One solution could be to use CssImportPreProcessor with RubySassProcessor. I could give it a try. Could you share the resource you are trying to process?

**Comment by magnyld** [comment]
Hi 

Thanks for your fast reply

I try to build Foundation from their sources, https://github.com/zurb/foundation/


I tried to use the CssImportPreProcessor but is a bit unsure how to set it up correct from the docs, http://wro4j.readthedocs.org/en/stable/ReusingProcessors/  says something about the ResourceUriLocators.

```
   static String readFile(String path, Charset encoding) throws IOException {
        byte[] encoded = Files.readAllBytes(Paths.get(path));
        return new String(encoded, encoding);
    }

    private String processSCSS(HttpServletRequest request, String scss) {
        Writer sassWriter = new StringWriter();

        CssImportPreProcessor cssImportPreProcessor = new CssImportPreProcessor();
        RubySassCssProcessor rubySassCssProcessor = new RubySassCssProcessor();

        String file = "/_dsf/contrib/js/foundation-5.5.3/scss/foundation.scss";
        Resource resource = Resource.create("foundation.scss", ResourceType.CSS);
        File f = new File(request.getServletContext().getRealPath(file));


        // Create the configuration object and use it for current context
        WroConfiguration config = new WroConfiguration();
        Context.set(Context.standaloneContext(), config);
        try {
            // Create injector which will inject all dependencies of the
            // processor
            Injector injector = new InjectorBuilder().build();


            // this will inject all required fields, after this point it is safe
            // to use processor outside of wro4j context.
            injector.inject(cssImportPreProcessor);
            injector.inject(rubySassCssProcessor);

            String foundationSrc = readFile(f.getAbsolutePath(), Charset.defaultCharset());

            // Do the actual processing
            Writer importWriter = new StringWriter();

            cssImportPreProcessor.process(resource, new StringReader(foundationSrc), importWriter);
            rubySassCssProcessor.process(resource, new StringReader(importWriter.toString() + scss), sassWriter);


        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            Context.unset();
        }

        return sassWriter.toString();
    }

```

Now I get an exception on 
```
 injector.inject(cssImportPreProcessor);
```


```
14:09:35.137 [http-nio-8080-exec-1] ERROR ro.isdc.wro.model.group.processor.Injector - Error while scanning @Inject annotation
java.lang.NullPointerException: null
	at ro.isdc.wro.model.group.processor.InjectorBuilder$10.create(InjectorBuilder.java:193) ~[wro4j-core-1.7.9.jar:1.7.9]
	at ro.isdc.wro.model.group.processor.InjectorBuilder$10.create(InjectorBuilder.java:191) ~[wro4j-core-1.7.9.jar:1.7.9]
	at ro.isdc.wro.model.group.processor.Injector.acceptAnnotatedField(Injector.java:135) [wro4j-core-1.7.9.jar:1.7.9]
	at ro.isdc.wro.model.group.processor.Injector.processInjectAnnotation(Injector.java:80) [wro4j-core-1.7.9.jar:1.7.9]
	at ro.isdc.wro.model.group.processor.Injector.inject(Injector.java:59) [wro4j-core-1.7.9.jar:1.7.9]
	at ro.isdc.wro.model.group.processor.Injector.acceptAnnotatedField(Injector.java:136) [wro4j-core-1.7.9.jar:1.7.9]
	at ro.isdc.wro.model.group.processor.Injector.processInjectAnnotation(Injector.java:80) [wro4j-core-1.7.9.jar:1.7.9]
	at ro.isdc.wro.model.group.processor.Injector.inject(Injector.java:59) [wro4j-core-1.7.9.jar:
```

complaining about
```

        return new InjectableUriLocatorFactoryDecorator(managerFactory.create().getUriLocatorFactory());
```

Any ideas?

Best regards Andreas

**Comment by alexo** [comment]
I'll give it a try and will come back with an example later... (probably tomorrow).

**Comment by magnyld** [comment]
Would you able to get CssImportPreProcessor to concatenate the sass files as expected and resolve the paths?

Best regards Andreas

**Comment by alexo** [comment]
Hi Andreas, 
sorry for taking longer than expected. 
I'm currently working on using the contribution from issue #888 which should solve your problem. 
I don't think that using CssImportPreProcessor is a good approach, since SASS handles import statement differently than CSS.

**Comment by magnyld** [comment]
Hi

Thanks again for looking into this, I tried that class out and it worked fine import/path wise
/scss/foundation/_settings.scss
/scss/foundation.scss

Then I get another problem with current sass version in wro4j,

The gem file for foundation 5.5.3 says 
gem "sass", "~> 3.4.0"
gem "compass", "1.0.0"


https://github.com/zurb/foundation-sites/issues/6148

```
Sass::SyntaxError: Invalid CSS after "...ules: $modules ": expected "}", was "!global;"
                 expected at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:1009
                 expected at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:956
                     tok! at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:951
                    block at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:463
          mixin_directive at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:165
        special_directive at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:153
                directive at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:126
              block_child at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:480
           block_contents at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:473
               stylesheet at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:58
                    parse at uri:classloader:/gems/sass-3.1.19/lib/sass/scss/parser.rb:27
                 _to_tree at uri:classloader:/gems/sass-3.1.19/lib/sass/engine.rb:327
                  to_tree at uri:classloader:/gems/sass-3.1.19/lib/sass/engine.rb:257
             visit_import at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:144
                    visit at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/base.rb:37
                    visit at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:18
  block in visit_children at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/base.rb:53
                      map at org/jruby/RubyArray.java:2300
           visit_children at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/base.rb:53
  block in visit_children at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:27
         with_environment at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:39
           visit_children at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:26
           block in visit at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/base.rb:37
               visit_root at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:47
                    visit at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/base.rb:37
                    visit at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:18
                    visit at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/visitors/perform.rb:7
                   render at uri:classloader:/gems/sass-3.1.19/lib/sass/tree/root_node.rb:20
                  _render at uri:classloader:/gems/sass-3.1.19/lib/sass/engine.rb:300
                   render at uri:classloader:/gems/sass-3.1.19/lib/sass/engine.rb:247
                    <top> at <script>:1539
```

Is there an easy way to bump the versions used?

Best regards Andreas

**Comment by alexo** [comment]
You can use most recent version easily by changing the dependencies in dependencyManagement section of your pom.xml. 

Btw, the 1.8.x branch uses updated versions of sass-gems and jruby.

**Comment by magnyld** [comment]
Just wanted to say that I am now compiling foundation sass successfully on runtime, 
```
        <dependency>
            <groupId>ro.isdc.wro4j</groupId>
            <artifactId>wro4j-core</artifactId>
            <version>1.7.9</version>
            
            <exclusions>
                <exclusion>
                    <groupId>me.n4u.sass</groupId>
                    <artifactId>sass-gems</artifactId>
                </exclusion>
                
                <exclusion>
                   <groupId>com.darrinholst</groupId>
                    <artifactId>sass-java-gems</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
                 
       
        <dependency>
            <groupId>ro.isdc.wro4j</groupId>
            <artifactId>wro4j-extensions</artifactId>
            <version>1.7.9</version>
            <exclusions>
                <exclusion>
                    <groupId>me.n4u.sass</groupId>
                    <artifactId>sass-gems</artifactId>
                </exclusion>
                
                <exclusion>
                   <groupId>com.darrinholst</groupId>
                    <artifactId>sass-java-gems</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        
        <dependency>
            <groupId>com.darrinholst</groupId>
            <artifactId>sass-java-gems</artifactId>
            <version>3.4.4.3</version>
        </dependency>

```

Thanks for all the help! Looking forward to the next release on maven central!

Best regards Andreas

**Comment by alexo** [comment]
Great news! Thanks and the update.

**Comment by driverpt** [comment]
Any ETA on this ?

**Comment by sterlp** [comment]
I created a pull request https://github.com/wro4j/wro4j/pull/1048 which should hopefully fix this issue. Could please somebody confirm and release a new version from wro4j?
